#!/usr/bin/env python3
"""The mechanical half of Session Handover.

An agent closing a session used to spend six or more tool calls rediscovering
things git already knows: what changed, which efforts those files belong to,
whether the log rows were added, and which paths to stage. That is checkable
work, so it belongs here rather than in an agent's context window. What is left
for the agent is the part that needs judgement: rewriting the effort note,
deciding what is worth keeping, and naming what went wrong.

Run it, read the report, do the TODOs, run it again until the checks pass.

    python3 System/scripts/handover.py            # report
    python3 System/scripts/handover.py --commit-cmd   # just the git line

It never writes to the vault and never runs git commit. It prints.
"""

from __future__ import annotations

import re
import subprocess
import sys
from datetime import date
from pathlib import Path

from vault_paths import VAULT

TODAY = date.today().isoformat()

# Files regenerated by build_views.py. They are staged with the commit but they
# are not evidence that a human step was done, so they never count as "changed".
GENERATED = {
    "Maps & Manuals/Active Context.md",
    "Maps & Manuals/Skill Map.md",
    "Ideaverse/Efforts/Efforts Index.md",
    "Ideaverse/Atlas/Atlas Index.md",
    "Ideaverse/Outputs/Outputs Index.md",
    "Ideaverse/Sources/Sources Index.md",
}


def is_generated(path: str) -> bool:
    """Files build_views.py writes. Staged with the commit, but never evidence
    that a human step was done."""
    return path in GENERATED or (
        path.startswith(".claude/skills/") and path.endswith("/SKILL.md")
    )


def git(*args: str) -> str:
    """Raw stdout with only the trailing newline removed.

    Deliberately not .strip(): porcelain status encodes the state in the first
    two columns, so a leading space is data. Stripping it shifts every column
    on the first line and silently eats the first character of that path.
    """
    out = subprocess.run(
        ["git", "-C", str(VAULT), *args], capture_output=True, text=True
    )
    return out.stdout.rstrip("\n")


def parse_frontmatter(path: Path) -> dict:
    """Same shape as vault_lint.parse_frontmatter, kept local so this script
    stays runnable on its own."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return {}
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return {}
    fm = {}
    for line in m.group(1).splitlines():
        mm = re.match(r"^([A-Za-z_]+):\s*(.*)$", line)
        if mm:
            fm[mm.group(1)] = mm.group(2).strip().strip('"')
    return fm


def changed_paths() -> list[tuple[str, str]]:
    """(status, path) for everything git sees, including untracked."""
    rows = []
    for line in git("status", "--porcelain=v1").splitlines():
        if len(line) < 4:
            continue
        status, path = line[:2].strip(), line[3:].strip()
        if path.startswith('"') and path.endswith('"'):
            path = path[1:-1].encode().decode("unicode_escape")
        rows.append((status or "?", path))
    return rows


def effort_of(path: str) -> str | None:
    """The effort folder a changed file belongs to, if any.

    Needs four components, not three: Ideaverse/Efforts/<folder>/<file>. With
    three, the third part is a file sitting directly in Efforts/ (the generated
    Efforts Index), and treating it as a folder invents an effort with no
    frontmatter and reports two TODOs against it that can never be satisfied.
    """
    parts = Path(path).parts
    if len(parts) >= 4 and parts[0] == "Ideaverse" and parts[1] == "Efforts":
        return f"{parts[0]}/{parts[1]}/{parts[2]}"
    return None


def has_dated_line(path: Path, day: str, after_marker: str | None = None) -> bool:
    """Does the file carry a line for `day`? Optionally only past a marker.

    Used for the append-only log files and for Outside View, where the check is
    'did this session add its entry' and the answer is one grep, not a read.
    """
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8")
    if after_marker:
        idx = text.find(after_marker)
        if idx == -1:
            return False
        text = text[idx:]
    return day in text


def commit_command(paths: list[str]) -> str:
    quoted = " \\\n ".join(f'"{p}"' for p in sorted(paths))
    return (
        "git commit -o -F <message-file> -- \\\n " + quoted
        if paths
        else "# nothing to commit"
    )


def system_edits() -> list[str]:
    """Uncommitted changes inside the vault's System/ checkout.

    System/ is a separate repository pinned to a version tag and gitignored by
    the vault, so `git status` in the vault reports nothing however much was
    edited there. An agent that edited a skill would be told the session had no
    changes and would commit nothing. Worse, the checkout is usually detached at
    a tag, so a commit made there is dangling and reaches nobody.

    The system is authored in a separate clone, not here. See
    Skills/Tools/Update System.md.
    """
    sysdir = VAULT / "System"
    if not (sysdir / ".git").exists():
        return []
    out = subprocess.run(
        ["git", "-C", str(sysdir), "status", "--porcelain=v1"],
        capture_output=True,
        text=True,
    )
    return [ln[3:].strip() for ln in out.stdout.splitlines() if ln.strip()]


def main() -> int:
    rows = changed_paths()
    paths = [p for _, p in rows]

    if "--commit-cmd" in sys.argv:
        print(commit_command(paths))
        return 0

    substantive = [p for p in paths if not is_generated(p)]
    generated = [p for p in paths if is_generated(p)]
    efforts = sorted(
        {e for p in paths if not is_generated(p) and (e := effort_of(p))}
    )

    out: list[str] = []
    add = out.append

    add("=" * 60)
    add(f"SESSION HANDOVER  ({TODAY})")
    add("=" * 60)

    stray = system_edits()
    if stray:
        add("")
        add("!! UNCOMMITTED EDITS INSIDE System/ -- these reach nobody")
        for p in stray:
            add(f"     System/{p}")
        add("   System/ is a separate repo pinned to a tag and gitignored here,")
        add("   so the vault commit below will not include any of it, and the")
        add("   checkout is detached so committing in place leaves a dangling")
        add("   commit. Move the work to the authoring clone and cut a version:")
        add("   Skills/Tools/Update System.md, section 'For the maintainer'.")

    # --- what moved -------------------------------------------------------
    add("")
    add(f"Changed, needing your judgement ({len(substantive)}):")
    for p in sorted(substantive):
        add(f"  {p}")
    if generated:
        add(f"Regenerated by build_views, no judgement needed ({len(generated)}).")
    if not paths:
        add("  nothing. If this session changed something, it is already committed.")

    # --- per effort -------------------------------------------------------
    add("")
    add("EFFORTS TOUCHED")
    if not efforts:
        add("  none. Skip steps 1 to 3.")
    for e in efforts:
        folder = VAULT / e
        note = folder / f"{Path(e).name}.md"
        log = folder / "Project_log.md"
        fm = parse_frontmatter(note)
        add(f"  {Path(e).name}")
        stale = "" if fm.get("updated") == TODAY else "  <-- TODO: set to today"
        add(f"    updated: {fm.get('updated', 'MISSING')}{stale}")
        nxt = fm.get("next", "")
        if not nxt:
            add("    next:    MISSING  <-- TODO: a concrete dated action")
        else:
            add(f"    next:    {nxt[:100]}{'...' if len(nxt) > 100 else ''}")
            if not re.search(r"\d{4}-\d{2}-\d{2}|\d{1,2} \w+ \d{4}", nxt):
                add("             <-- TODO: no date in next:. Themes are not actions")
        if log.exists():
            done = "ok" if str(log.relative_to(VAULT)) in paths else "TODO: add a row"
            add(f"    Project_log.md: {done}")

    # --- the vault-wide steps --------------------------------------------
    agent_log = VAULT / "Maps & Manuals/Agent Log.md"
    outside = VAULT / "Private/Outside View.md"
    marker = "NEW ENTRIES GO DIRECTLY BELOW THIS LINE"

    add("")
    add("VAULT-WIDE STEPS")
    al = "ok" if has_dated_line(agent_log, TODAY) else "TODO or say 'no mistakes'"
    add(f"  Agent Log, this session's mistakes: {al}")
    ov = "ok" if has_dated_line(outside, TODAY, marker) else "TODO"
    add(f"  Outside View, one observation:      {ov}")
    add("     (write under the marker; do not read the entries below it)")

    # --- outputs without a summary ---------------------------------------
    missing = [
        p
        for p in paths
        if p.endswith(".md")
        and "/Outputs/" in p
        and not parse_frontmatter(VAULT / p).get("summary")
    ]
    if missing:
        add("")
        add("OUTPUTS MISSING A summary: FIELD")
        for p in missing:
            add(f"  {p}  <-- agents read this field to decide whether to open the file")

    # --- the checklist ----------------------------------------------------
    add("")
    add("THE STEPS  (full note: System/Skills/Workflows/Session Handover.md)")
    for line in [
        "1. Rewrite each effort note to say what is TRUE NOW. Replace, do not append.",
        "2. Add one row to each Project_log.md. Newest at top. Never edit a row.",
        "3. Close every open question this session answered, by writing the answer in.",
        "4. Give each new output a real summary: field.",
        "5. Route it in Active Context if the topic is new, escalated or time-critical.",
        "6. Sweep this chat for facts that exist nowhere else. Apply the keep test:",
        "   keep commitments, constraints, identifiers, decisions, corrections.",
        "   Drop narration of work the files already show. Deadlines get a calendar",
        "   event, not a sentence in prose.",
        "7. Agent Log Section 2: this session's mistakes, one line each. 'None' is fine.",
        "8. Private/Outside View.md: one observation, or 'nothing new this session'.",
        "9. Run build_views.py, then vault_lint.py, then commit the paths below.",
        "10. Run sessions.py --handover to record that this session closed properly.",
        "11. Write the human wrap-up: what happened, and what only the owner can decide.",
    ]:
        add(f"  {line}")

    # --- the commit -------------------------------------------------------
    add("")
    add("COMMIT  (explicit paths; -o ignores anything a parallel session staged)")
    add("")
    add(commit_command(paths))
    add("")
    add("  End the message with:  Agent: <name and model>")

    unpushed = git("rev-list", "--count", "@{u}..HEAD").strip()
    if unpushed and unpushed != "0":
        add("")
        add(f"  Note: {unpushed} commit(s) not pushed. Ask before pushing.")

    print("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
