#!/bin/zsh
# Mechanical part of Weekly Maintenance. Run by hand, or via /weekly-maintenance in Claude Code.
# Full agent version: Skills/Workflows/Weekly Maintenance.md (/weekly-maintenance).
set -u
cd "$(dirname "$0")/.." || exit 1
WEEK=$(date +%Y-W%V)
NOTE="Ideaverse/Calendar/${WEEK} - Weekly Review.md"
LOG="scripts/logs/weekly-${WEEK}.log"
{
  echo "=== Weekly maintenance ${WEEK} ($(date)) ==="
  # Capture what was regenerated so the commit below can name those files
  # explicitly. Staging whole directories would sweep in a parallel
  # session's half-finished work, which has happened twice.
  BUILD_OUT=$(python3 scripts/build_views.py)
  print -r -- "$BUILD_OUT"
  python3 scripts/vault_lint.py
  LINT_STATUS=$?
  if [ ! -f "$NOTE" ]; then
    {
      echo "# ${WEEK} - Weekly Review (auto-stub)"
      echo ""
      echo "Generated by scripts/weekly_maintenance.sh. Run /weekly-maintenance in Claude Code to complete it."
      echo ""
      echo "## Movement this week (git)"
      git log --since="7 days ago" --oneline | sed 's/^/- /'
      echo ""
      echo "## Lint status"
      [ $LINT_STATUS -eq 0 ] && echo "Clean." || echo "ISSUES FOUND: see ${LOG}"
    } > "$NOTE"
    python3 scripts/vault_metrics.py >> "$NOTE"
    echo "created ${NOTE}"
  else
    python3 scripts/vault_metrics.py > /dev/null
  fi
  # Full agent pass (drafts the real weekly review) when the claude CLI is available
  CLAUDE_BIN="$(command -v claude 2>/dev/null || true)"
  [ -z "$CLAUDE_BIN" ] && [ -x "$HOME/.local/bin/claude" ] && CLAUDE_BIN="$HOME/.local/bin/claude"
  if [ -n "$CLAUDE_BIN" ]; then
    "$CLAUDE_BIN" -p "/weekly-maintenance" --permission-mode acceptEdits >> "scripts/logs/agent-${WEEK}.log" 2>&1 \
      || echo "agent pass failed (see agent-${WEEK}.log); mechanical results stand"
  else
    echo "claude CLI not found; mechanical pass only"
  fi
  # Stage only what this run produced: the weekly note and the files
  # build_views reported regenerating. The agent pass commits its own work
  # under step 12 of the workflow, so nothing here needs to catch it.
  typeset -a STAGE
  STAGE=()
  [ -f "$NOTE" ] && STAGE+=("$NOTE")
  while IFS= read -r line; do
    case "$line" in
      "regenerated: "*) f="${line#regenerated: }"; [ -f "$f" ] && STAGE+=("$f") ;;
    esac
  done <<< "$BUILD_OUT"
  if [ ${#STAGE[@]} -gt 0 ]; then
    # -o commits only these paths and ignores anything else already staged.
    git commit -o -q -m "Weekly maintenance ${WEEK}" -- "${STAGE[@]}" \
      || echo "nothing to commit"
  else
    echo "nothing this run produced; not committing"
  fi
  if ! git diff-index --quiet HEAD -- 2>/dev/null; then
    echo "note: other uncommitted changes left alone (another session may be live)"
  fi
  git remote get-url origin >/dev/null 2>&1 && git push -q || echo "no remote configured; skipping push"
} >> "$LOG" 2>&1
